version: "3.7"
services:
  app:
    image: mindfoundation/asc-studymonitor
    build:
      context: .
      args:
        - SOURCE_COMMIT=${SOURCE_COMMIT}
    expose:
      - 8000
    secrets:
      - asc-secret
    stop_signal: SIGINT
    restart: always

  mongo:
    image: mongo:4.2-bionic
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: integration
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - mongodb-data:/data/db

  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - URL=mind-foundation.org
      - SUBDOMAINS=asc-studymonitor
      - VALIDATION=http
      # - DNSPLUGIN=cloudflare #optional
      # - DUCKDNSTOKEN=<token> #optional
      - EMAIL=felix.peppert@mind-foundation.org
      # - DHLEVEL=2048 #optional
      - ONLY_SUBDOMAINS=true
      # - EXTRA_DOMAINS=<extradomains> #optional
      # - STAGING=false #optional
    volumes:
      - ./etc/letsencrypt:/config
      - ./static:/static
    ports:
      - 443:443
      - 80:80

  cache_warmer:
    build: cache-warmer/

volumes:
  mongodb-data:
    name: asc-mongodb-prod

secrets:
  asc-secret:
    file: asc-secret.json